# This is a basic workflow to help you get started with Actions

name: 'Plan Base'

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  pull_request:
    branches: [ stg ]
    paths:
    - "**"
    - "!.github/**"
    - "!.gitignore"
    - "!.pre-commit-config.yaml"
    - "!README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  terraform:
    name: 'terraform plan'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Configure aws credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BASE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BASE_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # Runs terraform stack VPC
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init VPC'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.2
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'vpc'
          tf_actions_comment: true
      - name: 'Terraform fmt VPC'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.2
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: 'vpc'
          tf_actions_comment: true
      - name: 'Terraform plan VPC'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.2
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'vpc'
          tf_actions_comment: true

      # Runs terraform stack KEY
      - name: 'Terraform Init KEY'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.2
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'key'
          tf_actions_comment: true
      - name: 'Terraform fmt KEY'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.2
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: 'key'
          tf_actions_comment: true
      - name: 'Terraform plan KEY'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.2
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'key'
          tf_actions_comment: true

      # Runs terraform stack ACM
      - name: 'Terraform Init ACM'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.2
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'acm'
          tf_actions_comment: true
      - name: 'Terraform fmt ACM'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.2
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: 'acm'
          tf_actions_comment: true
      - name: 'Terraform plan ACM'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.2
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'acm'
          tf_actions_comment: true